name: italclay
favicon: null
layout_spectrum: 0.48086
typography_spectrum: 0.49793
title: Homesite of Waterproofing Technology
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#161719'
    - '#ffffff'
    - '#7b6229'
    - '#caa532'
    - '#e9d467'
  brandStrength: 0.6572839487344027
  lightness: 0.8356090013403445
  saturation: 0.08140183170326054
  rhythmicContrast: 0.6984615316614509
purpose: []
