name: Italclay
favicon: null
layout_spectrum: 0.34578
typography_spectrum: 0.25528
title: 'http://italclay.com/wp-content/uploads/logo.png Homesite of Waterproofing Technology'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#161719'
    - '#ffffff'
    - '#7b6229'
    - '#caa532'
    - '#e9d467'
  brandStrength: 0.6572839487344027
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
